public class PatientMain extends javax.swing.JFrame {

    /**
     * Creates new form PatientMain
     */
    public PatientMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ToContact = new javax.swing.JButton();
        ToPatient = new javax.swing.JButton();
        ToInsurance = new javax.swing.JButton();
        ToPayment = new javax.swing.JButton();
        ToPayment1 = new javax.swing.JButton();
        ToPayment2 = new javax.swing.JButton();
        ToPayment3 = new javax.swing.JButton();
        ToPatient1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        ToContact.setText("Emergency Contact");
        ToContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToContactActionPerformed(evt);
            }
        });

        ToPatient.setText("Refill Prescription");
        ToPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToPatientActionPerformed(evt);
            }
        });

        ToInsurance.setText("Insurance");
        ToInsurance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToInsuranceActionPerformed(evt);
            }
        });

        ToPayment.setText("Payment Information");
        ToPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToPaymentActionPerformed(evt);
            }
        });

        ToPayment1.setText("Set Appointment");
        ToPayment1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToPayment1ActionPerformed(evt);
            }
        });

        ToPayment2.setText("Make Payment");
        ToPayment2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToPayment2ActionPerformed(evt);
            }
        });

        ToPayment3.setText("Past Medical History");
        ToPayment3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToPayment3ActionPerformed(evt);
            }
        });

        ToPatient1.setText("Patient");
        ToPatient1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToPatient1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(410, 410, 410)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ToPayment3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ToPayment1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ToContact, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ToInsurance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ToPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(132, 132, 132)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ToPayment2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ToPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(413, 413, 413)
                        .addComponent(ToPatient1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ToContact, ToInsurance, ToPatient, ToPayment, ToPayment1});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ToPatient1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ToContact, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ToInsurance, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ToPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(ToPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ToPayment2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ToPayment3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ToPayment1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ToContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToContactActionPerformed

        Emergency_contactPatient ad = new Emergency_contactPatient();
        ad.setVisible(true);

    }//GEN-LAST:event_ToContactActionPerformed

    private void ToPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToPatientActionPerformed

        Refill ad = new Refill();
        ad.setVisible(true);

    }//GEN-LAST:event_ToPatientActionPerformed

    private void ToInsuranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToInsuranceActionPerformed
        InsurancePatient ad = new InsurancePatient();
        ad.setVisible(true);
    }//GEN-LAST:event_ToInsuranceActionPerformed

    private void ToPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToPaymentActionPerformed

        Payment_InformationPatient ad = new Payment_InformationPatient();
        ad.setVisible(true);

    }//GEN-LAST:event_ToPaymentActionPerformed

    private void ToPayment1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToPayment1ActionPerformed
        PatientAppointment ad = new PatientAppointment();
        ad.setVisible(true);
    }//GEN-LAST:event_ToPayment1ActionPerformed

    private void ToPayment2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToPayment2ActionPerformed
        Make_Payment ad = new Make_Payment();
        ad.setVisible(true);
    }//GEN-LAST:event_ToPayment2ActionPerformed

    private void ToPayment3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToPayment3ActionPerformed
        PatientHistory ad = new PatientHistory();
        ad.setVisible(true);
    }//GEN-LAST:event_ToPayment3ActionPerformed

    private void ToPatient1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToPatient1ActionPerformed
        PatientPatient ad = new PatientPatient();
        ad.setVisible(true);
    }//GEN-LAST:event_ToPatient1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ToContact;
    private javax.swing.JButton ToInsurance;
    private javax.swing.JButton ToPatient;
    private javax.swing.JButton ToPatient1;
    private javax.swing.JButton ToPayment;
    private javax.swing.JButton ToPayment1;
    private javax.swing.JButton ToPayment2;
    private javax.swing.JButton ToPayment3;
    // End of variables declaration//GEN-END:variables
}
